### ISSUE TITLE
Adding AppendAllNeighbors functionality

### ISSUE THREAD

**Issue by natemiller** [spatstat/s2#10]
Thank you for this package. Thus far I have used it for pretty basic grouping of spatial points. I'm now trying to apply spatial operations (distances calculations etc.) on a global dataset, where the comparisons are only important for points within the vicinity of one another. I would like to perform an initial join using neighboring s2cells and then apply the spatial calculations just for those points in neighboring s2cells.  I had a quick look and I didn't seen an implementation of `AppendAllNeighbors` in the package. Is there any thought to adding this or any of the neighbor functions (`GetEdgeNeighbors`, `GetVertexNeighbors`)? That would be incredibly useful.

**Comment by rubak** [comment]
Actually, I plan to give the package a major overhaul this spring and summer. The current version is based on Google's old S2 source code which was released around 2009 without further official updates. In late 2017 the new official S2 version was released and we need to switch to this code base soon. Of course this doesn't help you right now, but I want to make the move before developing any new features.

**Comment by natemiller** [comment]
Thank you for the update. Definitely look forward to following the package updates

**Comment by rubak** [comment]
I have now transferred the development of the new S2 package to the r-spatial team and you should [go there](https://github.com/r-spatial/s2/) to watch for further development. This package will receive no further updates.
