### ISSUE TITLE
S2CellIdFromLatLng method is missing

### ISSUE THREAD

**Issue by odvratnozgodan** [spatstat/s2#8]
Hello,
I have forked the project and added the code to support the S2CellIdFromLatLng. 
Is there any instructions or script for making the package/library?

Thank you in advance.

**Comment by rubak** [comment]
Hi,
I have been away from the project for a while, but your message just reminded me to update the repo with some old code only committed locally on my laptop. If you have made some meaningful working code you could just make a pull request and I can add the code to the package if it is appropriate.

It is just a standard R package and if you don't add any new source files the makefile should take care of everything when you build the package. If you use RStudio you probably just have to go to the "build" tab and click "Install and Restart". With plain R in the terminal you can run `R CMD build` and `R CMD install` as appropriate to make it work.
I have mainly used the package to do calculations underlying `spatstat.sphere` and left this very raw on purpose. My original goal was to only have the C++ code in this package and update it very rarely, and then have other packages use the C++ code, but I didn't succeed in implementing this in a satisfactory way.

**Comment by odvratnozgodan** [comment]
Hello,
Thank you for your help. I have managed to expose the `S2CellIdFromLatLng` method in the library and to build and install it locally. I am going to test the code and if it works as expected I will make a pull request. Also it would be great if you could push your local code to the repo so that I can fetch it and work on the latest code.

I have a couple of questions regarding the library implementation. Specifically I'm interested what was the reason that you decided for using matrices for passing the data into the methods?
Eg. you used `NumericMatrix` for passing the data to S2CellIdFromPoint, but from my experience using R for data science most libraries work with `dataframes` or `tibbles` and they seem more intuitive and are quite common in the data analysis pipelines.
So if you don't mind I would like to change those parts of the library too(though it isn't a quick refactor).

Anyway, great job on the library!

Cheers

**Comment by rubak** [comment]
I did push my old stuff already, so the current GitHub version is the most recent one.

Using matrices to represent collections of points is completely standard and will not be changed unless there are very good reasons. Matrices are used everywhere in the standard spatial package `sf` and this works nicely with the tidyverse. See the vignettes/documentation in `sf` for details of how spatial data is represented.
